### ISSUE TITLE
Shape Error for Sequence Classification Model

### ISSUE THREAD

**Issue by rajshah4** [g8a9/ferret#10]
* ferret version: ferret-xai-0.3.3
* Python version: 3.6 (Google Colab)
* Operating System: Google Colab

### Description

I tried to use a fine tuned model on imdb and getting a shape error:
```
model2 = AutoModelForSequenceClassification.from_pretrained("lvwerra/distilbert-imdb")
tokenizer2 = AutoTokenizer.from_pretrained("lvwerra/distilbert-imdb")
bench = Benchmark(model2, tokenizer2)
explanations = bench.explain("You look stunning!")
```
The error I am getting is:
`shape '[50, 1, 1, 6]' is invalid for input of size 6`

I like how you are integrating all these libraries - transformer-interpret might be useful to work with

**Comment by heatxg** [comment]
I am facing a similar issue. 

ferret-xai-0.3.4
Python: 3.7.12
OS: Ubuntu 20.04.2

**Comment by g8a9** [comment]
Hi @rajshah4 and @heatxg, I think the issue was related to a misaligned batch size when computing the forward pass in Integrated Gradients.

b975c04 should have fixed that, let me know if you have any further issues.

**Comment by rajshah4** [comment]
Thanks so much, it works for me now.
