### ISSUE TITLE
Getting error when running on GPU

### ISSUE THREAD

**Issue by santhoshkolloju** [g8a9/ferret#12]
Getting an error Input and output should be on same device

**Comment by g8a9** [comment]
Hi, we are not supporting evaluation on GPU at the moment. We plan to release it by the end of the month.

**Comment by g8a9** [comment]
Hello! I just want to notify you that we now support inference ([v0.4.0](https://github.com/g8a9/ferret/releases/tag/0.4.0)) on GPU 🥳
