### ISSUE TITLE
incorrect tokenization with roberta tokenizer

### ISSUE THREAD

**Issue by ritwikmishra** [g8a9/ferret#24]
* ferret version: 0.4.1
* Python version: 3.8.16
* Operating System: Ubuntu

### Description

I observed that the tokenization is incorrect in the final generated table.

### What I Did

```
from ferret import Benchmark
from transformers import AutoModelForSequenceClassification, AutoTokenizer
device = 'cuda:0'

name = "cardiffnlp/twitter-roberta-base-offensive"
model = AutoModelForSequenceClassification.from_pretrained(name).to(device)
tokenizer = AutoTokenizer.from_pretrained(name)

bench = Benchmark(model, tokenizer)
explanations = bench.explain('laura loomer screamed at me', target=1)
df = bench.get_dataframe(explanations)

print(df)
```

Output
```
Token                                   <s>         l      aura       Ġlo      omer  Ġscreamed       Ġat       Ġme          </s>                                                                              
Partition SHAP                 9.165922e-08 -0.092576 -0.074982 -0.102104  0.194431   0.260761  0.256109 -0.019037 -3.055307e-08
LIME                           0.000000e+00 -0.064617 -0.199529 -0.041211 -0.075026   0.440958  0.094847  0.083813  0.000000e+00
Gradient                       1.240649e-01  0.052262  0.118494  0.070542  0.098837   0.309795  0.097929  0.060810  6.726743e-02
Gradient (x Input)             5.900680e-02 -0.012240 -0.362078  0.028704  0.004122  -0.029875  0.245232 -0.114939  1.438036e-01
Integrated Gradient           -5.347527e-02 -0.066218 -0.228668 -0.047713  0.098191   0.223275 -0.182781 -0.085795 -1.388342e-02
Integrated Gradient (x Input)  0.000000e+00  0.058598 -0.249950 -0.107572 -0.073952   0.288827  0.133013  0.088088  0.000000e+00
```

However, actual tokenization (using ```tokenizer.tokenize(word)```) is as follows
```
laura ['l', 'aura']
loomer ['l', 'oom', 'er']
screamed ['sc', 'ream', 'ed']
at ['at']
me ['me']
```

The tokenization is correct in case of other models like ```cardiffnlp/bertweet-base-hate``` or  ```Hate-speech-CNERG/hindi-abusive-MuRIL```.

**Comment by g8a9** [comment]
Hi there, thank you for reaching out.
Unfortunately, I am not able to replicate your issue. By running your code in [this colab](https://colab.research.google.com/drive/1KG7CpceHpuR1Reu8hfEqoUMXsqcPTFom?usp=sharing) the tokenization is consistent among the bare tokenizer and the table returned by ferret.

Can you give it a look and let me know? :) 

Also, please note that the tokenizer you use splits words differently whether they start with a leading whitespace or not. E.g., `tokenizer.tokenize(" screamed") != tokenizer.tokenize("screamed")`.
Go [here](https://discuss.huggingface.co/t/bpe-tokenizers-and-spaces-before-words/475/2) for a bit of a context on why this is happening.

**Comment by ritwikmishra** [comment]
@g8a9 I used the following code
```
for word in 'laura loomer screamed at me'.split():
    print(tokenizer.tokenize(word))
```
the output is the one I mentioned above

Actually I need to know which words are broken into subwords. For that I am tokenizing each word separately.

**Comment by g8a9** [comment]
I see. Then I am pretty sure your issue is linked to the way the tokenizer splits words that have a leading space or not (see the article I mentioned in the previous post).

In other words, 

```python
for word in 'laura loomer screamed at me'.split():
    print(tokenizer.tokenize(word))
```

is not going to give you the correct subwords, since it will artificially remove the space from in-the-middle words.

Again, as an example, the correct way your tokenizer is tokenizing the word `screamed` when it's in the middle of a sentence as in `laura loomer screamed at me' is with a single token. However, if you remove the leading space and try `tokenizer.tokenize("screamed")` you will have three tokens.

**Comment by g8a9** [comment]
I think the correct way of finding which word was split into subwords is:
```python
encodings = tokenizer("laura loomer screamed at me")
encodings.word_ids()
```

where each integer in the resulting list corresponds to a word.

**Comment by ritwikmishra** [comment]
Thank you

I was going to go with ```return_offsets_mapping``` flag

But ```word_ids()``` seems like a better option.

Thanks
